### ISSUE TITLE
Bug in classifier.py (AttributeError: 'NearestNeighbors' object has no attribute 'predict')

### ISSUE THREAD

**Issue by 0mp** [0mp/io-touchpad#129]
```
sudo ./app.py --system 32 -sym a
Use your touchpad as usual. Have a nice day!
```
Now I draw my user-defined _a_ symbol. I tought it to the program using `sudo ./app.py -l 5 -sym a`.
```

New portion of events:
Event # 1       out of 81 in the list. x: 2401 y: 2827
Event # 2       out of 81 in the list. x: 2355 y: 2848
Event # 3       out of 81 in the list. x: 2340 y: 2861
Event # 4       out of 81 in the list. x: 2304 y: 2909
Event # 5       out of 81 in the list. x: 2270 y: 2978
Event # 6       out of 81 in the list. x: 2241 y: 3063
Event # 7       out of 81 in the list. x: 2221 y: 3167
Event # 8       out of 81 in the list. x: 2210 y: 3286
Event # 9       out of 81 in the list. x: 2219 y: 3404
Event # 10      out of 81 in the list. x: 2245 y: 3527
...

classifing...
Traceback (most recent call last):
  File "./app.py", line 95, in <module>
    main()
  File "./app.py", line 93, in main
    system_bitness, symbol_name)
  File "/home/matangi/Documents/io-touchpad/app/threads/application.py", line 60, in application_thread
    classifier)
  File "/home/matangi/Documents/io-touchpad/app/threads/application.py", line 118, in send_points_to_interpreter
    item = classifier.classify(signal_list)
  File "/home/matangi/Documents/io-touchpad/app/classifier/classifier.py", line 163, in classify
    symbol_candidate = self.learning_models[""].predict([feature_vector])[0]
AttributeError: 'NearestNeighbors' object has no attribute 'predict'
```

Relates #127.

**Comment by 0mp** [comment]
It is more broken then I thought.

Event the hardcoded symbols don't work now:

```
sudo ./app.py -s 32
Use your touchpad as usual. Have a nice day!

New portion of events:
Event # 1       out of 53 in the list. x: 2318 y: 2582
Event # 2       out of 53 in the list. x: 2307 y: 2564
Event # 3       out of 53 in the list. x: 2302 y: 2562
Event # 4       out of 53 in the list. x: 2296 y: 2561
Event # 5       out of 53 in the list. x: 2290 y: 2610
Event # 6       out of 53 in the list. x: 2282 y: 2686
Event # 7       out of 53 in the list. x: 2276 y: 2785
Event # 8       out of 53 in the list. x: 2269 y: 2911
Event # 9       out of 53 in the list. x: 2258 y: 3062
Event # 10      out of 53 in the list. x: 2243 y: 3248
...

classifing...
Traceback (most recent call last):
  File "./app.py", line 95, in <module>
    main()
  File "./app.py", line 93, in main
    system_bitness, symbol_name)
  File "/home/matangi/Documents/io-touchpad/app/threads/application.py", line 60, in application_thread
    classifier)
  File "/home/matangi/Documents/io-touchpad/app/threads/application.py", line 118, in send_points_to_interpreter
    item = classifier.classify(signal_list)
  File "/home/matangi/Documents/io-touchpad/app/classifier/classifier.py", line 163, in classify
    symbol_candidate = self.learning_models[""].predict([feature_vector])[0]
AttributeError: 'NearestNeighbors' object has no attribute 'predict'
```

**Comment by 0mp** [comment]
`sudo ./app.py -s 32` works on master so the problem is in the #127.

We should have tests for this.

- [ ] Add this issue to tests.

**Comment by michal7352** [comment]
Bug was caused by not exchange files from old format.
