### ISSUE TITLE
Error when starting 64 hardcoded symbols on 32-bit architecture

### ISSUE THREAD

**Issue by 0mp** [0mp/io-touchpad#135]
We should handle this error somehow.

```
Traceback (most recent call last):
  File "./app.py", line 115, in <module>
    main()
  File "./app.py", line 113, in main
    system_bitness, symbol_name)
  File "/home/matangi/Documents/io-touchpad/app/threads/application.py", line 41, in application_thread
    system_bitness=system_bitness)
  File "/home/matangi/Documents/io-touchpad/app/classifier/classifier.py", line 78, in __init__
    self.learning_models.append(pickle.load(file_with_model))
  File "sklearn/neighbors/binary_tree.pxi", line 1129, in sklearn.neighbors.ball_tree.BinaryTree.__setstate__ (sklearn/neighbors/ball_tree.c:9307)
  File "sklearn/neighbors/binary_tree.pxi", line 228, in sklearn.neighbors.ball_tree.get_memview_ITYPE_1D (sklearn/neighbors/ball_tree.c:2867)
ValueError: Buffer dtype mismatch, expected 'ITYPE_t' but got 'long long'
```

**Comment by 0mp** [comment]
#154
