### ISSUE TITLE
Error in learning session of SIZE=3 (ValueError: Expected n_neighbors <= n_samples,  but n_samples = 3, n_neighbors = 5)

### ISSUE THREAD

**Issue by 0mp** [0mp/io-touchpad#140]
First I do learning with sudo `./app.py -l 3 -s small_p`.

Then I run `sudo ./app.py` and get an output like this:

```
Use your touchpad as usual. Have a nice day!

New portion of events:
Event # 1       out of 75 in the list. x: 3016 y: 2653
Event # 2       out of 75 in the list. x: 3036 y: 2617
Event # 3       out of 75 in the list. x: 3037 y: 2615
Event # 4       out of 75 in the list. x: 3042 y: 2626
Event # 5       out of 75 in the list. x: 3070 y: 2682
Event # 6       out of 75 in the list. x: 3094 y: 2754
Event # 7       out of 75 in the list. x: 3120 y: 2849
Event # 8       out of 75 in the list. x: 3147 y: 2972
Event # 9       out of 75 in the list. x: 3166 y: 3106
Event # 10      out of 75 in the list. x: 3184 y: 3253
...

classifing...
Traceback (most recent call last):
  File "./app.py", line 93, in <module>
    main()
  File "./app.py", line 91, in main
    system_bitness, symbol_name)
  File "/home/matangi/Documents/io-touchpad/app/threads/application.py", line 60, in application_thread
    classifier)
  File "/home/matangi/Documents/io-touchpad/app/threads/application.py", line 118, in send_points_to_interpreter
    item = classifier.classify(signal_list)
  File "/home/matangi/Documents/io-touchpad/app/classifier/classifier.py", line 175, in classify
    symbol_candidate = models[""].predict([feature_vector])[0]
  File "/usr/local/lib/python3.4/dist-packages/sklearn/neighbors/classification.py", line 147, in predict
    neigh_dist, neigh_ind = self.kneighbors(X)
  File "/usr/local/lib/python3.4/dist-packages/sklearn/neighbors/base.py", line 361, in kneighbors
    (train_size, n_neighbors)
ValueError: Expected n_neighbors <= n_samples,  but n_samples = 3, n_neighbors = 5
```

Relates #127

**Comment by piotrekp1** [comment]
@michal7352 does the algorithims compare symbols with constant number of neighbors? for example.. 5? if so i would suggest to not change parameters of the model and just increase the minimal possible cardinality of training set.

**Comment by 0mp** [comment]
It wasn't like this before.
