### ISSUE TITLE
import subcommand crashes when trying to load a file which doesn't exist

### ISSUE THREAD

**Issue by 0mp** [0mp/io-touchpad#188]
```
sudo ./app.py import asd                                                                
importing in classifier
Traceback (most recent call last):
  File "./app.py", line 360, in <module>
    main()
  File "./app.py", line 356, in main
    _import_settings(args)
  File "./app.py", line 315, in _import_settings
    classifier.import_files(args.settings_name)
  File "/home/matangi/Documents/io-touchpad/app/classifier/classifier.py", line 172, in import_files
    file_with_export = open(export_path, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'classifier/data/user-defined/exports/_asd'
```

#187

**Comment by 0mp** [comment]
It deleted all my user-defined symbols...
