### ISSUE TITLE
Bug in app/classifier/classifier.py (ValueError: Buffer dtype mismatch, expected 'ITYPE_t' but got 'long long')

### ISSUE THREAD

**Issue by 0mp** [0mp/io-touchpad#65]
I got an error like this:

```
Available devices:
/dev/input/event0:    AT Translated Set 2 keyboard
/dev/input/event1:    SynPS/2 Synaptics TouchPad
/dev/input/event2:    Video Bus
/dev/input/event3:    Power Button
/dev/input/event4:    Sleep Button
/dev/input/event5:    Lid Switch
/dev/input/event6:    Power Button
/dev/input/event7:    PC Speaker
/dev/input/event8:    HDA Digital PCBeep
/dev/input/event9:    HDA SIS966 Mic
/dev/input/event10:    HDA SIS966 Headphone
Select the device event number [0-10]: 1
Touchpad specification: min/max x: 1472/5472, min/max y: 1408/4448, min/max pressure 0/255.
Use your touchpad as usual. Have a nice day!
Traceback (most recent call last):
  File "./app.py", line 68, in <module>
    main()
  File "./app.py", line 66, in main
    application.application_thread(thread_queue, learning_mode, training_size)
  File "/home/matangi/Documents/io-touchpad/app/threads/application.py", line 30, in application_thread
    clsf = classifier.Classifier()
  File "/home/matangi/Documents/io-touchpad/app/classifier/classifier.py", line 19, in __init__
    self.learning_model = pickle.load(file_with_model)
  File "sklearn/neighbors/binary_tree.pxi", line 1129, in sklearn.neighbors.ball_tree.BinaryTree.__setstate__ (sklearn/neighbors/ball_tree.c:9307)
  File "sklearn/neighbors/binary_tree.pxi", line 228, in sklearn.neighbors.ball_tree.get_memview_ITYPE_1D (sklearn/neighbors/ball_tree.c:2867)
ValueError: Buffer dtype mismatch, expected 'ITYPE_t' but got 'long long'
```

It seems like @michal7352 saved some classifier data in some sort of a binary format which is not compatible with 32-bit systems.

Relates #58

**Comment by michal7352** [comment]
How to fix it ?

**Comment by 0mp** [comment]
@michal7352 Well, I thought you might have an idea for that. In that case I'l try to debug it one my own since I am the only one here with a 32-bit system.

**Comment by 0mp** [comment]
OK, I got it. The problem is that the current format of the files is platform dependent. It means that I cannot use symbols defined on a 64-bit system when I use a 32-bit system.
